### ISSUE TITLE
[Feature request] Начисление баллов нашедшему книгу, если подавший запрос в раздел «Ищу» не отвечает

### ISSUE THREAD

**Issue by Kristinita** [twirpx/twirpx-com-public#80]
### 1. Проблема

я просматривал старые запросы в разделе «Ищу». Некоторые книги мне удалось найти. Примеры:

+ [**Волосюк В.К. Кравченко В.Ф. Статистическая теория радиотехнических систем дистанционного зондирования и радиолокации**](http://www.twirpx.com/look/41483/#comment-1364936),
+ [**Ремонт, техническое обслуживание и метрологическое обеспечение весов на железнодорожном транспорте**](http://www.twirpx.com/look/39659/#comment-1363334).

*(Да, я понимаю, что следовало бы выложить книги на Twirpx; и выложу, если по данной проблеме будет вынесено положительное решение.)*

Вроде бы книги, выложенные мной, удовлетворяют требованиям запросчиков. Но прошли месяцы, а баллы мне не передают. И притом, смотрю, не только я выкладываю книги по запросам, но не получаю баллов.

### 2. Предложение

Если:

1. Выложенная книга полностью удовлетворяет требованиям запросчика. В том числе тот же год издания, формат и т. д.
1. С момента, как запрошенная книга была выложена на Twirpx, прошло 2 месяца. На мой взгляд, достаточный срок, чтобы запросчик мог выразить своё мнение о выложенной ему книге.

То нашедшему книгу по запросу будет передано вознаграждение в размере, который указал запросчик. Со счёта запросчика или кого-либо другого, особой роли для нашедшего не играет.

#### 3.1. Для нашедшего

1. Баллы.

#### 3.2. Для сайта

1. Сайт пополнится новыми книгами.
1. При стабильном начислении баллов за найденные книги на сайте будет больше людей, готовых помочь с поиском. А когда баллы не перечисляют, пользователи могут бросить продолжать искать книги по запросам.
1. «Завалы» в разделе «Ищу» должны уменьшиться.

Спасибо.

**Comment by twirpx** [comment]
Вы можете обратиться к любому из модераторов с просьбой закрытия запроса и передачи баллов, коль скоро автор никак не реагирует.
