### ISSUE TITLE
[Feature request] Изменение URL при поисковом запросе

### ISSUE THREAD

**Issue by Kristinita** [twirpx/twirpx-com-public#81]
### 1. Запрос

Было бы неплохо, если б на Twirpx URL изменялся при поисковом запросе.

### 2. Примеры

Допустим, я подал в Google запрос `Саша Великолепная!`. URL в Google будет выглядеть следующим образом:

+ `https://www.google.com/search?q=Саша+Великолепная!`

В Twirpx же, какой бы поисковый запрос не ввёл пользователь, URL остаётся неизменным:

+ `http://www.twirpx.com/search/`

#### 3.1. Пользователей

я пользуюсь плагином для Sublime Text [**Bang Search**](https://github.com/bsoun/bang-search). Когда мне нужно найти какую-либо книгу, при помощи этого плагина я делаю запрос на 5 сайтов одновременно. Чтобы найти книгу на Twirpx, мне приходится заходить на сайт через браузер и опять писать поисковый запрос.

#### 3.2. Программистов

Добавление текста запроса в URL расширит возможности сайта для программистов. Появится возможность управлять поисковой выдачей Twirpx.

Спасибо.

**Comment by twirpx** [comment]
В результатах поиска см. "Поисковый запрос: **постоянная ссылка**"
